# Generated by Django 5.0.3 on 2024-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_options_article_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='muscle_type',
            field=models.CharField(choices=[('HANDS', 'Руки'), ('BREAST', 'Грудь'), ('LEGS', 'Ноги'), ('SHOULDERS', 'Плечи'), ('BACK', 'Спина')], default='HANDS', max_length=10, verbose_name='Тип мышц'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок статьи'),
        ),
    ]
