# Generated by Django 5.0.3 on 2024-03-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_remove_article_muscle_type_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
    ]
