# Generated by Django 5.0.3 on 2024-03-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
