# Generated by Django 5.0.3 on 2024-03-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(blank=True, default=18, verbose_name='возраст'),
        ),
    ]
