# Generated by Django 5.0.3 on 2024-03-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_member',
            field=models.BooleanField(default=False, verbose_name='Член клуба'),
        ),
    ]
