# Generated by Django 5.0.3 on 2024-03-17 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание тарифа')),
            ],
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('fitness', 'Тренер тренажерного зала'), ('pool', 'Инструктор бассейна'), ('yoga', 'Инструктор йоги'), ('groups', 'Тренер групповых тренировок')], max_length=100, verbose_name='Должность')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, upload_to='get_path_avatar_for_employee', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.rate', verbose_name='Тариф')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.reviews', verbose_name='Родитель')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer', verbose_name='фильм')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='RatingTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.ratingstar', verbose_name='звезда')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'Рейтинг тренера',
                'verbose_name_plural': 'Рейтинг тренеров',
            },
        ),
        migrations.CreateModel(
            name='TrainerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='trainers/images/', verbose_name='Изображение')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Фото тренра',
                'verbose_name_plural': 'Фото тренеров',
            },
        ),
    ]
