# Generated by Django 5.0.3 on 2024-03-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_seasontickets_buytickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buytickets',
            options={'verbose_name': 'Купленный абонемент', 'verbose_name_plural': 'Купленные абонементы'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-price'], 'verbose_name': 'Тариф тренера', 'verbose_name_plural': 'Тарифы тренеров'},
        ),
        migrations.AlterModelOptions(
            name='seasontickets',
            options={'ordering': ['-price'], 'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer', verbose_name='тренер'),
        ),
    ]
