# Generated by Django 5.0.3 on 2024-03-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_alter_buytickets_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='get_path_avatar_for_trainer', verbose_name='Аватар'),
        ),
    ]
