# Generated by Django 5.0.3 on 2024-03-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_alter_trainer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytickets',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
