# Generated by Django 5.0.3 on 2024-03-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_orderticket_delete_buytickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='end',
            field=models.DateTimeField(blank=True, verbose_name='Конец'),
        ),
    ]
