# Generated by Django 5.0.3 on 2024-03-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_alter_orderticket_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerimages',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
