# Generated by Django 5.0.3 on 2024-03-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0012_alter_trainerimages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerimages',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fitness_app.trainer', verbose_name='Тренер'),
        ),
    ]
