# Generated by Django 5.0.3 on 2024-03-20 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0015_alter_reviews_trainer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='count_minutes',
            field=models.SmallIntegerField(null=True, verbose_name='Количество минут'),
        ),
        migrations.CreateModel(
            name='OrderTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('end', models.DateTimeField(blank=True, verbose_name='Конец')),
                ('status', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', to='fitness_app.rate')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', to='fitness_app.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Купленное занятие',
            },
        ),
    ]
