# Generated by Django 5.0.3 on 2024-03-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0017_alter_ordertraining_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonTickets',
            new_name='Abonement',
        ),
    ]
