# Generated by Django 5.0.3 on 2024-03-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0018_rename_seasontickets_abonement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAbonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('end', models.DateTimeField(blank=True, verbose_name='Конец')),
                ('status', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('abonement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonements', to='fitness_app.abonement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Купленный абонемент',
                'verbose_name_plural': 'Купленные абонементы',
            },
        ),
        migrations.DeleteModel(
            name='OrderTicket',
        ),
    ]
