# Generated by Django 5.0.3 on 2024-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0019_orderabonement_delete_orderticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderabonement',
            options={'verbose_name': 'Забронированный абонемент', 'verbose_name_plural': 'Забронированные абонементы'},
        ),
        migrations.AlterModelOptions(
            name='ordertraining',
            options={'verbose_name': 'Забронированное занятие', 'verbose_name_plural': 'Забронированные занятия'},
        ),
        migrations.AddField(
            model_name='orderabonement',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
