# Generated by Django 5.0.3 on 2024-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0021_alter_ordertraining_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertraining',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
