# Generated by Django 5.0.3 on 2024-03-31 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0024_alter_ratingstar_options_alter_ratingtrainer_trainer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв о тренерах', 'verbose_name_plural': 'Отзывы о тренерах'},
        ),
        migrations.CreateModel(
            name='CalendarTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='fitness_app.trainer')),
            ],
            options={
                'verbose_name': 'Календарь тренера',
                'verbose_name_plural': 'Календарь тренеров',
            },
        ),
    ]
