# Generated by Django 5.0.3 on 2024-03-31 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0025_alter_reviews_options_calendartrainer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendartrainer',
            options={'ordering': ['-start'], 'verbose_name': 'Календарь тренера', 'verbose_name_plural': 'Календарь тренеров'},
        ),
        migrations.AlterField(
            model_name='calendartrainer',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='конец тренировки'),
        ),
        migrations.AlterField(
            model_name='calendartrainer',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало тренировки'),
        ),
        migrations.AlterField(
            model_name='calendartrainer',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='fitness_app.trainer', verbose_name='Тренер'),
        ),
    ]
