# Generated by Django 5.0.3 on 2024-03-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0026_alter_calendartrainer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartrainer',
            name='status',
            field=models.BooleanField(default=False, verbose_name='занято'),
        ),
    ]
